# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w05lvwNTvewOsi1d0FZCYIiMRUL3dc_G
"""

!pip install tensorflow==2.12.0 # Instala o TensorFlow
!pip install opencv-python # Instala o OpenCV para processamento de imagens
!pip install matplotlib # Instala o Matplotlib para visualização

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5

!gdown --id 1n_oKgR81BJtqk75b00eAjdv03qVCQn2f # Download do COCO128 usando gdown (mais confiável)
!unzip -q coco128.zip -d ../datasets  # Descompacta o dataset na pasta datasets, suprimindo a saída detalhada com -q
!wget https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5s.pt # Download de pesos pré-treinados

!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --cache

!python detect.py --source ../datasets/coco128/images/train2017/000000000009.jpg --weights runs/train/exp/weights/best.pt --conf 0.5